
services:
  db:
    image: mysql:8.0
    container_name: inventory_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: inventory
      MYSQL_USER: inventory_user
      MYSQL_PASSWORD: inventory_password
    ports:
      - "3306:3306"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/mysql

  backend:
    image: tomcat:10.1-jre21
    container_name: inventory_backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend/target/inventory-backend.war:/usr/local/tomcat/webapps/inventory.war:ro
    depends_on:
      - db

  frontend:
    image: eclipse-temurin:21-jre
    container_name: inventory_frontend
    hostname: cachyos-x8664
    ipc: host
    environment:
      - DISPLAY=${DISPLAY}
      - BACKEND_HOST=backend
      - XAUTHORITY=/tmp/xauth
      - _JAVA_AWT_WM_NONREPARENTING=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${XAUTHORITY:-/tmp/null}:/tmp/xauth:ro
      - ./frontend/target:/app/target:ro
    working_dir: /app
    command: >
      sh -c "apt-get update && apt-get install -y libxext6 libxrender1 libxtst6 libxi6 libx11-6 fontconfig && java -Djava.awt.headless=false -jar target/inventory-frontend-1.0-SNAPSHOT.jar"
    depends_on:
      - backend

volumes:
  db_data:
